services:
  webserver:
    image: ghcr.io/ngimbisarah243/webserver:latest
    build:
      context: ../../
      dockerfile: src/Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080" ]
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
